core version in RBF

diff --git a/bin/jtbeta b/bin/jtbeta
--- a/bin/jtbeta
+++ b/bin/jtbeta
@@ -100,7 +100,10 @@ if (git status --short | grep -i "^ M " > /dev/null); then
     exit 1
 fi
 
-version_ok.sh > /dev/null || echo "Missing version tag"; exit $?
+if ! version_ok.sh > /dev/null; then
+    echo "Missing version tag"
+    exit $?
+fi
 
 if [ $WEEK_COMMIT != $MASTER_COMMIT ]; then
     echo The $MASTER branch is not at the same commit as the week branch.
