jtframe mra: support for only reversing 8-bit ROMs in a 8/16 merged region

diff --git a/bin/jtbin2mr b/bin/jtbin2mr
--- a/bin/jtbin2mr
+++ b/bin/jtbin2mr
@@ -75,12 +75,17 @@ if [ -d $JTBIN/games ]; then cp -r $JTBIN/games $ROOT; fi
 
 # Copy the files to MiSTer
 if [ "$V" = -v ]; then echo -e "\nCopying the files to MiSTer"; fi
-sshpass -p $MISTERPASSWD ssh -l $MRUSER mister.home "rm -rf /media/fat/_JTBIN"
-if sshpass -p $MISTERPASSWD scp -r $TEMP/* $MRUSER@${MRHOST}:/media/fat; then
-    rm -rf $TEMP
+if [ -d /media/$USER/MiSTer_Data ]; then
+    echo "MiSTer SD card detected"
+    rm -rf /media/$USER/MiSTer_Data/_JTBIN
+    cp -r $TEMP/_JTBIN /media/$USER/MiSTer_Data || echo "Copy to MiSTer SD card failed"
 else
-    echo "Copy to MiSTer failed. Temporary files in " $TEMP
-    exit 1
+    sshpass -p $MISTERPASSWD ssh -l $MRUSER mister.home "rm -rf /media/fat/_JTBIN"
+    if sshpass -p $MISTERPASSWD scp -r $TEMP/* $MRUSER@${MRHOST}:/media/fat; then
+        rm -rf $TEMP
+    else
+        echo "Copy to MiSTer failed. Temporary files in " $TEMP
+        exit 1
+    fi
 fi
-
 rm -rf $TEMP
