More jtcore functionality - copies to JTBIN, JTALPHA - Support for cores that don't start with jt - copies to a network-connected MiSTer device

diff --git a/bin/jtcore b/bin/jtcore
--- a/bin/jtcore
+++ b/bin/jtcore
@@ -42,29 +42,42 @@ JTCORE compilation tool. (c) Jose Tejada 2019-2023, @topapate
     -pocket     compiles the PocketFPGA version
 
     General options
+
     --arc           Converts the first MRA found that uses this core to ARC
                     and copies it to /media/$USER/MIST/core.arc
+    --corestamp     Sets the date string attached to the RBF file name. Defaults to today
+    --credits       Defines NOSOUND, MISTER_DEBUG_NOHDMI and NOMAIN. Sets MiSTer as target.
+    -mrq            Compiles MiSTer with no HDMI nor logo but with sound
+    --mrpasswd      Sets the SSH pasword to use on MiSTer
+    --private       Uses red for OSD and allows copying to JTALPHA
     --program | -p  programs the FPGA via JTAG
     --quick|-q      quick compilation. Defines NOSOUND and JTFRAME_OSD_NOLOGO
                     Disables JTFRAME_CREDITS and HQ2X.
     --quicker|-qq   same as -q but it also disabled HDMI output and sets MiSTer as target
     --seed          sets random seed for compilation
+    --sim           prepares Quartus simulation
     --skip | -s     skips the compilation but executes the rest of the commands
+    --showmacros    Shows the macros used for compilation and exits
     --target|-t <target>
                     specifies the target platform
     --rename        name used for copying the RBF file into the SD card
-    --help          displays this message
     --verbose | -v  verbose
+
+    --help          displays this message
 EOF
    exit 0
 }
 
 ARC=FALSE
+CORESTAMP=$(date +"%Y%m%d")
 EXT=rbf
 FAIL=0
 GIT=FALSE
 MACROS=
+MISTERPASSWD=1
+MRHOST=MiSTer.home
 OUTPUTDIR=output_files
+PRIVATE=0
 PRJ=
 PROG=FALSE
 RENAME=
@@ -98,10 +111,17 @@ function parse_args {
     while [ $# -gt 0 ]; do
         case "$1" in
             --arc) ARC=TRUE;;
+            --corestamp)
+                shift
+                CORESTAMP=$1;;
+            --credits)
+                MACROS="$MACROS NOSOUND MISTER_DEBUG_NOHDMI NOMAIN"
+                TARGET=mister;;
             --def|-d)
                 shift
                 MACROS="$1 $MACROS"
                 ;;
+            --git | -g) GIT=TRUE;;
             --prog | -p) PROG=TRUE;;
             --prog-only | -w)
                 PROG=TRUE
@@ -116,10 +136,33 @@ function parse_args {
                 UNMACROS="$UNMACROS JTFRAME_CREDITS"
                 TARGET=mister
                 GIT=FALSE;;
-            -mister | -mr)
+            -mr)
                 TARGET=mister;;
-            -mist|-sidi|-neptuno|-mc2|-mcp|-pocket)
+            -mister|mist|-sidi|-neptuno|-mc2|-mcp|-pocket)
                 TARGET=${1:1};;
+            --mrpasswd)
+                shift
+                MISTERPASSWD=$1;;
+            -mrq)
+                MACROS="$MACROS JTFRAME_OSD_NOLOGO JTFRAME_NOHQ2X MISTER_DEBUG_NOHDMI"
+                GIT=FALSE
+                TARGET=mister;;
+            --private)
+                PRIVATE=1
+                MACROS="$MACROS JTFRAME_OSDCOLOR=(6'h20)"
+                if [ -z "$JTALPHA" ]; then
+                    echo "Error: you must defined the environment variable JTALPHA to use --private"
+                    exit 1
+                fi
+                if [ ! -d "$JTALPHA" ]; then
+                    echo "Error: JTALPHA points to a non existent folder $JTALPHA"
+                    exit 1
+                fi
+                ;;
+            --sim)
+                SIM=TRUE;;
+            --showmacros)
+                SHOWMACROS=1;;
             --target|-t)
                 shift
                 TARGET=$1;;
@@ -170,6 +213,12 @@ if [ "$JTROOT" = "" ]; then
     exit 1
 fi
 
+# The FTP folder can be set in the project's $JTROOT/setprj.sh file
+# This is the MiSTer folder to which files will be copied to via ssh
+if [ -z "$FTP_FOLDER" ]; then
+    FTP_FOLDER=JT
+fi
+
 cd $JTROOT
 MODULES=$JTROOT/modules
 JTFRAME=$MODULES/jtframe
@@ -179,8 +228,6 @@ PRJCOMMIT=$(git rev-parse --short HEAD)
 if (git status --short | grep "^ M " > /dev/null); then
     PRJCOMMIT="$PRJCOMMIT-dirty"
 fi
-
-CORESTAMP=$(date +"%Y%m%d")
 
 if [ ! -e "$JTFRAME" ]; then
     echo -e "${rBG}ERROR:${NC}${wBG} cannot locate jtframe folder.${NC}"
@@ -214,6 +261,13 @@ shift
 if [ -z "$CORE_FOLDER" ]; then
     CORE_FOLDER=$(basename $JTROOT)
     CORE_FOLDER=${CORE_FOLDER^^}
+fi
+
+if [ $GIT = TRUE ]; then
+    if (git status --short | grep "^ M " > /dev/null); then
+        echo "Error: cannot use -git if git isn't clean. Commit and try again"
+        exit 1
+    fi
 fi
 
 OUTPUTDIR=output_files
@@ -268,20 +322,21 @@ function copy_templates {
     datestr=$(date "+%H:%M:%S %B %e, %Y")
     # Replace core name and path to modules
     # do not leave a space in the line below sedstr!
-    sedstr='s/${CORENAME}/'${PRJ}'/g;s/${DATE}/'${datestr}'/g;s/${MODULES}/'$(escape_bars ${MODULES})'/g;s/${PRJPATH}/'$(escape_bars ${PRJPATH})'/g;'\
+    CORENAME=`echo $CORENAME | tr [:upper:] [:lower:]`
+    sedstr='s/${CORENAME}/'${CORENAME}'/g;s/${DATE}/'${datestr}'/g;s/${MODULES}/'$(escape_bars ${MODULES})'/g;s/${PRJPATH}/'$(escape_bars ${PRJPATH})'/g;'\
 's/${OUTPUTDIR}/'${OUTPUTDIR}'/g'
-    sed "$sedstr" $JTFRAME/target/$TARGET/$TARGET.qpf > $PRJPATH/$TARGET/jt${PRJ}.qpf
-    sed "$sedstr" $JTFRAME/target/$TARGET/$TARGET.qsf > $PRJPATH/$TARGET/jt${PRJ}.qsf
+    sed "$sedstr" $JTFRAME/target/$TARGET/$TARGET.qpf > $PRJPATH/$TARGET/${CORENAME}.qpf
+    sed "$sedstr" $JTFRAME/target/$TARGET/$TARGET.qsf > $PRJPATH/$TARGET/${CORENAME}.qsf
     # TCL in HDL folder is always appended
-    TCL=$PRJPATH/hdl/jt${PRJ}.tcl
+    TCL=$PRJPATH/cfg/${CORENAME}.tcl
     MACROS_FILE=$PRJPATH/cfg/macros.def
-    QSF=$PRJPATH/$TARGET/jt${PRJ}.qsf
+    QSF=$PRJPATH/$TARGET/${CORENAME}.qsf
     if [ -e $TCL ]; then
         cat $TCL >> $QSF
     fi
     # TCL in platform folder is added if it exists
-    if [ -e $PRJPATH/$TARGET/jt${PRJ}.tcl ]; then
-        cat $PRJPATH/$TARGET/jt${PRJ}.tcl >> $QSF
+    if [ -e $PRJPATH/$TARGET/${CORENAME}.tcl ]; then
+        cat $PRJPATH/$TARGET/${CORENAME}.tcl >> $QSF
     fi
     # Add definitions in "macros" files
     if [ -e $MACROS_FILE ]; then
@@ -303,8 +358,8 @@ function copy_templates {
         fi
         cat $JTFRAME/target/mister/sys/sys_top.sdc >> $PRJPATH/$TARGET/sys_top.sdc
         # Adds local SDC file if exists (only MiSTer)
-        if [ -e $PRJPATH/mister/jt${PRJ}.sdc ]; then
-            cat <(echo -e "\n") $PRJPATH/mister/jt${PRJ}.sdc >> $PRJPATH/$TARGET/sys_top.sdc
+        if [ -e $PRJPATH/mister/${CORENAME}.sdc ]; then
+            cat <(echo -e "\n") $PRJPATH/mister/${CORENAME}.sdc >> $PRJPATH/$TARGET/sys_top.sdc
         fi
     fi
 }
@@ -386,6 +441,7 @@ if [ $SKIP_COMPILE = FALSE ]; then
     mkdir -p $JTROOT/log/$TARGET
     LOG="$JTROOT/log/$TARGET/jt$PRJ.log"
     echo Log file: $LOG
+    `eval parse_macros bash | grep CORENAME | tr -d \" `
     copy_templates
     echo -e "\nset_global_assignment -name seed $SEED" >> jt$PRJ.qsf
     if [ $SIM = FALSE ]; then
@@ -455,9 +511,9 @@ esac
 cd $JTROOT
 mkdir -p releases/$TARGET
 if [ -z $RENAME ]; then
-    SHORT=jt${PRJ}
+    SHORT=${CORENAME}
 else
-    SHORT=jt$RENAME
+    SHORT=$RENAME
 fi
 
 # date stamp is only added to MiSTer output
@@ -489,6 +545,25 @@ if [ $TARGET = pocket ]; then
 fi
 
 cp $RBF releases/$TARGET/$RELEASE.$EXT
+
+######################################################################################
+# Adds the file to the JTALPHA folder if it is a succesful compilation for MiSTer
+if [[ $FAIL = 0 && -n "$JTALPHA" && -d "$JTALPHA" && $TARGET == mister && \
+      $MACROS != *NOSOUND* && \
+      $MACROS != *MISTER_DEBUG_NOHDMI* && $PRIVATE = 1 ]]; then
+    JTALPHA_OUTPUT=$JTALPHA/$PRJ/cores/$PRJCOMMIT
+    mkdir -p $JTALPHA_OUTPUT
+    cp $RELEASE.rbf $JTALPHA_OUTPUT/jt$PRJ.$EXT -v
+    echo git tag -f alpha_$RELEASE
+    git tag -f alpha_$RELEASE
+    cd $JTALPHA
+    git add $JTALPHA_OUTPUT
+    # The latest commit can be found following the 'latest' symbolic link
+    rm -f $JTALPHA/$PRJ/cores/latest
+    ln -sr $JTALPHA_OUTPUT $JTALPHA/$PRJ/cores/latest
+    git add $JTALPHA/$PRJ/cores/latest
+    cd -
+fi
 
 ######################################################################################
 # Copy the file to the SD card. The SD card must have the same name as the target platform
@@ -537,6 +612,64 @@ if [[ -d /media/$USER/${TARGET^^} && $TARGET != pocket ]]; then
 elif [ $TARGET != pocket ]; then
     echo "No SD card detected on /media/$USER/${TARGET^^}. Skipping the RBF copy."
 fi
+
+# If Mr is online, copy the file to the _Arcade/cores folder using MiSTer's SSH password
+if [ $TARGET = mister ]; then
+    if ping $MRHOST -w 1 -c 1 > /dev/null; then
+        sshpass -p $MISTERPASSWD scp $RELEASE.rbf root@${HOST}:/media/fat/_${FTP_FOLDER}/cores
+    fi
+fi
+
+# Copy to JTBIN
+if [[ ! -z "$JTBIN" && -e "$JTBIN" && $GIT = TRUE && $FAIL = 0 ]]; then
+    if [[ $TARGET = mister ]]; then
+        BINFOLDER=$JTBIN/$TARGET/$PRJ
+        BINRBF=$BINFOLDER/releases/${RELEASE}.$EXT
+        mkdir -p $BINFOLDER/releases
+    else
+        BINFOLDER=$JTBIN/$TARGET
+        BINRBF=$JTBIN/$TARGET/${SHORT}.$EXT
+        mkdir -p $BINFOLDER
+    fi
+    cp $RELEASE.rbf $BINRBF -v
+    # if [ -n "$SEED_SUFFIX" ]; then
+    #     cp $RELEASE.rbf ${BINRBF}${SEED_SUFFIX}.rbf -v
+    # fi
+    git tag -f $RELEASE
+    # keep a log of compiled versions
+    if [ -e $BINFOLDER/version.log ]; then
+        sed -i /$RELEASE/d  $BINFOLDER/version.log
+    fi
+    echo -e ${RELEASE}"\t"$PRJCOMMIT >> $BINFOLDER/version.log
+    # Add to git but don't commit
+    cd $JTBIN
+    git add -f $BINRBF
+    if [ $TARGET = mister ]; then
+        OTHER=$(append_if_exists rom/{$PRJ/build_rom.sh,$PRJ/build_rom.ini,build_rom_$PRJ.bat} doc/jt$PRJ.txt )
+        OTHER="$OTHER $(append_if_exists $JTROOT/doc/jt$PRJ.md $JTROOT/README.md $JTROOT/README.txt )"
+        # remove blanks
+        OTHER=${OTHER## }
+        if [ -n "$OTHER" ]; then
+            cp $OTHER $BINFOLDER;
+        fi
+        # Add the main MRA file to git too
+        MAINMRA=$(grep --files-with-matches jt$PRJ $MRA/*.mra | head -n 1)
+        MRACNT=$(find $BINFOLDER/releases -name "*mra" | wc -l)
+        if [[ -z "$MAINMRA" && $MRACNT = 0 ]]; then
+            echo "Warning: No MRA for jt$PRJ found in $MRA and no MRA files in $(pwd)"
+        else
+            NEWMRA="$BINFOLDER"/releases/$(basename "$MAINMRA")
+            pwd
+            if [[ $MRACNT = 0 || (-e "$NEWMRA" && "$NEWMRA" -ot "$MRA/$MAINMRA") ]]; then
+                # There was no MRA or the file present was older
+                cp -v "$MAINMRA" "$NEWMRA"
+                git add "$NEWMRA"
+            fi
+        fi
+    fi
+    cd - > /dev/null
+fi
+rm -f $RELEASE.rbf
 
 ###########################################
 ## Program the target device via JTAG
