jtframe mra generates setnames.txt so xmlstarlet is not used in jtreg. xmlstarlet doesn't work with file names containing '

diff --git a/bin/jtreg b/bin/jtreg
--- a/bin/jtreg
+++ b/bin/jtreg
@@ -2,15 +2,11 @@
 START_TIME=$(date +%s)
 CORE=$1
 
+if [ -z "$CORE" ]; then echo "Missing core name"; exit 1; fi
+if [ ! -d "$CORES/$CORE" ]; then echo "No core named $CORE in $CORES"; exit 1; fi
+
 jtframe mra $CORE
-
-# Get the core name
-eval `jtframe cfgstr $CORE --output=bash`
-CORENAME=${CORENAME,,}
-
-# Find all supported set names for the core
-SETNAMES=$(find $JTROOT/release/mra -name "*.mra" -print0 | xargs -0 -l \
-    xmlstarlet sel -t --var sp="' '" -m misterromdescription -i rbf="'$CORENAME'" -v setname -v \$sp )
+SETNAMES=`cat $CORES/$CORE/ver/setnames.txt`
 
 if [ -z "$SETNAMES" ]; then
     echo "No MAME set supported for $CORENAME ($CORE)"
@@ -22,7 +18,7 @@ mkdir -p $REGDIR || exit $?
 cd $REGDIR
 
 export JTFRAME_REGRESSION=1
-parallel --delay 0.5 jtsim -sysname $CORE -video 500 -dir -setname ::: $SETNAMES
+parallel --delay 0.5 jtsim -sysname $CORE -video 500 -dir -skipROM -setname ::: $SETNAMES
 END_TIME=$(date +%s)
 COMPILE_TIME=$[$END_TIME - $START_TIME]
 HOURS=$[$COMPILE_TIME / 3600]
